// package-lock.json.
//
// This test exists because of a specific failure, and it is worth writing down.
// A lockfile generated by a plain `npm install` records only the optional
// binaries for the machine that ran it — here, linux-x64. `npm ci` on any other
// platform then installs wrangler with no workerd binary for itself and no
// error, and the build fails somewhere later with a missing module.
//
// `npm install --package-lock-only` resolves from the registry's metadata
// instead of from this machine, and writes every platform's entry. That is the
// command to use when this file needs regenerating, and this test is what
// notices if someone regenerates it the other way.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const lock = JSON.parse(readFileSync(path.join(ROOT, "package-lock.json"), "utf8"));
const manifest = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8"));

/** The name each entry is keyed by, without the node_modules/ prefix. */
function packages(match) {
  return Object.keys(lock.packages)
    .filter(Boolean)
    .map((key) => key.replace(/^node_modules\//, ""))
    .filter((name) => name.includes(match));
}

test("the lockfile is for this package, at a version npm ci understands", () => {
  assert.equal(lock.name, manifest.name);
  assert.ok(lock.lockfileVersion >= 2, "npm ci needs lockfileVersion 2 or later");
  assert.deepEqual(
    lock.packages[""].devDependencies,
    manifest.devDependencies,
    "the lockfile and package.json disagree — npm ci will refuse to install",
  );
});

test("it carries every platform's binaries, not just the one that generated it", () => {
  // workerd is the one that matters: it is the runtime wrangler shells out to,
  // and it ships as a per-platform binary package.
  const workerd = packages("workerd-");
  for (const platform of [
    "@cloudflare/workerd-linux-64",
    "@cloudflare/workerd-linux-arm64",
    "@cloudflare/workerd-darwin-arm64",
  ]) {
    assert.ok(
      workerd.includes(platform),
      `${platform} is missing — regenerate with: npm install --package-lock-only`,
    );
  }

  // esbuild is the same shape, and is what bundles the Worker.
  const esbuild = packages("@esbuild/");
  assert.ok(
    esbuild.includes("linux-arm64") || esbuild.some((n) => n.endsWith("linux-arm64")),
    "the lockfile has no arm64 esbuild — it was resolved on one machine",
  );
});
